# Generated by Django 5.0 on 2024-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_pk_id', models.CharField(max_length=100, unique=True)),
                ('intra_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.URLField(blank=True)),
                ('otp_number', models.CharField(blank=True, max_length=6, null=True)),
                ('bio', models.TextField(blank=True, default='')),
            ],
        ),
    ]
